[package]
name = "osvm"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_derive = "1.0.210"
serde_json = "1.0.128"
libc = "0.2"
bincode = "*"

[profile.release]
opt-level = 3
lto = true